export { Login } from './login'
export { Registration } from './registration'
export { Profile } from './profile'
export { Main } from './main'
export { NotFound } from './404'
export { NotResponding } from './500'